### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by JDSECO** [WildKillBill/Billz_7_Days_To_Die_Mods#1]
Don’t work for me. I put in a helmet with light and when I turn on still hearing all like before.
I see a requirement for the buff in buffs.xml
```
<effect_group>
				<requirements>
					<requirement name="!HasBuff" buff="twitch_buffDeafen"/>
					<requirement name="!HasBuff" buff="twitch_buffVoteDeafen"/>
				</requirements>
					<triggered_effect trigger="onSelfBuffUpdate" state="Deafened" enabled="true"/>
			</effect_group>
```

Why this requirement of twitch_buffDeafen???

Unnecesary because not all of us use this.

**Comment by NebTR** [comment]
That code was supposed to counteract when twitch deafened ended but didn't seem to work when it ended and just left in cause it didn't affect the earplugs but I removed the code for it. It still seems to work for me I can't replicate it not working since I've been using it all day and currently using it so I can't really do much besides removing code that isn't necessary. If it still not working (as of updating my mod) please post your logs as well.

**Comment by NebTR** [comment]
After careful thought and consideration, it's possible that with multiple head armor mods, you have to hold F to select the multiple toggle armor mods.
